# Site settings
ref: CSCD71
title: Blockchains and Decentralized Applications
edition: Winter 2025
description: "The course is meant to expose students to Web3 by covering the technical aspects of blockchain technologies and smart contracts. The course will have three learning outcomes. First, the students will learn how to build blockchains based on different consensus. Secondly, they will learn how to develop decentralized applications using smart contracts. Finally, they will learn about the current challenges of blockchain technologies such as scalability, interoperability and privacy. The course will be co-taught with David Liu, UTSC CS alumni and Founder of Uniblock and will feature guest speakers from the industry."
website: https://thierrysans.me/CSCD71/
github: https://github.com/ThierrySans/CSCD71
slack: https://join.slack.com/t/cscd71-w25/shared_invite/zt-2y9cdxgjn-8dq409xP3ZaetRJMxGN_BA

instructor:
  name: Thierry Sans
  website: https://thierrysans.github.io/
  github: ThierrySans
  hours: Mon 1-3 PM
  location: IA 4124
  contact: Element only (no email)

assistants:
    # - name: Nikhil Lakhwani
    #   contact: "&#110;&#105;&#107;&#104;&#105;&#108;&#46;&#108;&#97;&#107;&#104;&#119;&#97;&#110;&#105;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
    #   hours: Tue 12:00-13:00
    #   location: IC 404
  
timings:
    - section: Lecture
      time: Tue 13:00-15:00
      location: IC 230
    - section: TUT01
      time: Wed 13:00-14:00
      location: AA 204
    - section: TUT02
      time: Thu 15:00-16:00
      location: AA 204
        
first: 20250106